language: java
dist: trusty
sudo: false

cache:
  directories:
  - .autoconf
  - $HOME/.m2

jdk:
  - oraclejdk8
  - openjdk8

install:
  - mvn clean compile assembly:single -q

script:
  - java -jar target/xcat-app-jar-with-dependencies.jar --version