language: java

cache:
  directories:
  - .autoconf
  - $HOME/.m2

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6

install:
  - mvn clean compile assembly:single

script:
  - java -cp target/demo-0.0.1-SNAPSHOT.jar-with-dependencies.jar --version