language: java

cache:
  directories:
  - .autoconf
  - $HOME/.m2

jdk:
  - oraclejdk8
  - openjdk8

install:
  - mvn clean compile assembly:single

script:
  - java -jar target/demo-0.0.1-SNAPSHOT.jar-with-dependencies.jar --version